require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NotesController, type: :controller do

  let(:valid_attributes) { FactoryGirl.attributes_for(:note, user_id: @admin.id) }
  let(:invalid_attributes) { FactoryGirl.attributes_for(:note, user_id: nil) }

  describe "POST #create" do
    before :each do
      @project = FactoryGirl.create(:project)
      @admin = FactoryGirl.create(:admin)
    end
    context "with valid params" do
      login_admin
      it "creates a new Note" do
        expect {
          post :create, params: {resource_controller: "projects", resource_id: @project.id, note: valid_attributes}
        }.to change(Note, :count).by(1)
      end

      it "assigns a newly created note as @note" do
        post :create, params: {resource_controller: "projects", resource_id: @project.id, note: valid_attributes}
        expect(assigns(:note)).to be_a(Note)
        expect(assigns(:note)).to be_persisted
      end
    end

    context "with invalid params" do
      it "if the user is not signed in will not save" do
        expect{
          post :create, params: {resource_controller: "projects", resource_id: @project.id, note: invalid_attributes}}.to change(Note, :count).by(0)
      end

      it "recieves a 302 response" do
        post :create, params: {resource_controller: "projects", resource_id: @project.id, note: invalid_attributes}
        expect(response.status).to eq(302)
      end
    end
  end

  describe "PUT #update" do
    before :each do
      @project = FactoryGirl.create(:project)
      @admin = FactoryGirl.create(:admin)
      @note = @project.notes.create(valid_attributes)
    end

    context "with admin" do
      login_admin
      let(:new_attributes) { FactoryGirl.attributes_for(:note, text: "new")}

      it "updates the requested note" do
        put :update, params: {resource_controller: "projects", resource_id: @project.id, id: @note.id, note: new_attributes}
        @note.reload
        expect(@note.text).to eq("new")
      end

      it "assigns the requested note as @note" do
        put :update, params: {resource_controller: "projects", resource_id: @project.id, id: @note.id, note: new_attributes}
        expect(assigns(:note)).to eq(@note)
      end
    end

    context "with user" do
      login_user
      let(:new_attributes) { FactoryGirl.attributes_for(:note, text: "new")}
      it "assigns the note as @note" do
        @note = @project.notes.create(valid_attributes)
        put :update, params: {resource_controller: "projects", resource_id: @project.id, id: @note.id, note: invalid_attributes}
        expect(assigns(:note)).to eq(@note)
      end

      it "updates the requested note" do
        put :update, params: {resource_controller: "projects", resource_id: @project.id, id: @note.id, note: new_attributes}
        @note.reload
        expect(@note.text).to eq("new")
      end
    end

    context "with no user signed in" do
      it "recieves a 302 response" do
        @note = @project.notes.create(valid_attributes)
        put :update, params: {resource_controller: "projects", resource_id: @project.id, id: @note.id, note: invalid_attributes}
        expect(response.status).to eq(302)
      end
    end
  end

  describe "DELETE #destroy" do
    before :each do
      @project = FactoryGirl.create(:project)
      @admin = FactoryGirl.create(:admin)
      @note = @project.notes.create(valid_attributes)
    end

    context "with admin" do
      login_admin
      it "destroys the requested note" do
        expect {
          delete :destroy, params:  {resource_controller: "projects", resource_id: @project.id, id: @note.id}
        }.to change(Note, :count).by(-1)
      end

      it "recieves a 302 response" do
        delete :destroy, params:  {resource_controller: "projects", resource_id: @project.id, id: @note.id}
        expect(response.status).to eq(302)
      end
    end

    context "with user" do
      login_user
      it "raises a Pundit::NotAuthorizedError" do
        expect {
        delete :destroy, params: {resource_controller: "projects", resource_id: @project.id, id: @note.id}
        }.to raise_error(Pundit::NotAuthorizedError)
      end
    end
  end

end
