require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TasksController, type: :controller do

  let(:valid_params) {FactoryGirl.attributes_for(:task, :project_id => @project.id)}

  let(:invalid_params) { FactoryGirl.attributes_for(:task, :name => nil)}


  before (:each) do
    @project = FactoryGirl.create(:project)
      @task = Task.create! valid_params
  end

  # This should return the minimal set of attributes required to create a valid
  # Task. As you add validations to Task, be sure to
  # adjust the attributes here as well.

  describe "GET #index" do

    context "non-registered user" do
        it "will redirect to login page" do
          get :index, params: {:resource_controller => "projects", :resource_id => @project.id }
          expect(response.status).to eq(302)
        end
      end

    context "user" do
      login_user

      it " will have a succesful response" do
        get :index, params: {:resource_controller => "projects", :resource_id => @project.id }
        expect(response.status).to eq(200)
      end

      it " will render the :index template " do
        get :index, params: {:resource_controller => "projects", :resource_id => @project.id }
        expect(response).to render_template("index")
      end

      it "will assign the resource.tasks as @tasks " do
        get :index, params: {:resource_controller => "projects", :resource_id => @project.id }
        expect(assigns(:tasks)).to eq([@task])
      end
    end

    context "admin" do
      login_admin

      it " will have a successful response " do
        get :index, params: {:resource_controller => "projects", :resource_id => @project.id }
        expect(response.status).to eq(200)
        end

      it " will render the :index template " do
        get :index, params: {:resource_controller => "projects", :resource_id => @project.id }
        expect(response).to render_template("index")
        end

      it "will assign the resource.tasks as @tasks " do
        get :index, params: {:resource_controller => "projects", :resource_id => @project.id }
        expect(assigns(:tasks)).to eq([@task])
        end
      end
    end

  describe "GET #show" do


    context "non-registered user" do
      it "will redirect to login page" do
      get :show, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
        expect(response.status).to eq(302)
      end
    end

    context "admin" do
      login_admin
      it "will have a succesful response" do
        get :show, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
        expect(response.status).to eq(200)
      end

      it "renders the :show template" do
        get :show, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
        expect(response).to render_template("show")
        end

      it "assigns the requested task as @task" do
        get :show, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
        expect(assigns(:task)).to eq(@task)
        end
      end

    context "user" do
      login_user
      it "will have a succesful response" do
        get :show, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
        expect(response.status).to eq(200)
        end

      it "renders the :show template" do
        get :show, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
        expect(response).to render_template("show")
        end

      it "assigns the requested task as @task" do
        get :show, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
        expect(assigns(:task)).to eq(@task)
        end
      end
    end

  describe "GET #new" do

    context "non-registered user" do
      it "will redirect to login page" do
      get :new, params: {:resource_controller => "projects", :resource_id => @project.id}
        expect(response.status).to eq(302)
      end
    end

    context "admin" do
      login_admin
    it "have a succesful response" do
      get :new, params: {:resource_controller => "projects", :resource_id => @project.id}
        expect(response.status).to eq(200)
      end

    it "assigns a new task as @task" do
      get :new, params: {:resource_controller => "projects", :resource_id => @project.id}
      expect(response).to render_template("new")
      end

    it "assigns a new task as @task" do
      get :new, params: {:resource_controller => "projects", :resource_id => @project.id}
      expect(assigns(:task)).to be_a_new(Task)
      end
    end
  end
  #
  describe "GET #edit" do

    context "admin" do
      login_admin

      it "have a succesful response" do
        get :edit, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
          expect(response.status).to eq(200)
        end

      it "it renders the :edit template" do
        get :edit, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
        expect(response).to render_template("edit")
        end

      it "assigns a new task as @task" do
        get :edit, params: {:resource_controller => "projects", :resource_id => @project.id, :id => @task.to_param}
        expect(assigns(:task)).to eq(@task)
        end
      end
    end

  describe "POST #create" do
    context "admin" do
      login_admin

        context "with valid params" do
          it "creates a new Task" do
            expect {
              post :create, params: {:resource_controller => "projects", :resource_id => @project.id, task: valid_params}
            }.to change(Task, :count).by(1)
          end

          it "creates a new Task" do
            expect {
              post :create, params: {:resource_controller => "projects", :resource_id => @project.id, task: valid_params}
            }.to change(Task, :count).by(1)
          end

          it "assigns a newly created task as @task" do
            post :create, params: {:resource_controller => "projects", :resource_id => @project.id, task: valid_params}
            expect(assigns(:task)).to be_a(Task)
            expect(assigns(:task)).to be_persisted
          end

          it "redirects to the created task" do
            post :create, params: {:resource_controller => "projects", :resource_id => @project.id, task: valid_params}
            expect(response).to redirect_to(task_path(id: Task.last))
          end
        end

        context "with invalid params" do

          it "will not increase the count of Tasks" do
            expect {
              post :create, params: {:resource_controller => "projects", :resource_id => @project.id, task: invalid_params}
            }.to_not change(Task, :count)
          end
          it "assigns a newly created but unsaved task as @task" do
            post :create, params: {:resource_controller => "projects", :resource_id => @project.id, task: invalid_params}
            expect(assigns(:task)).to be_a_new(Task)
          end

          it "re-renders the 'new' template" do
            post :create, params: {:resource_controller => "projects", :resource_id => @project.id, task: invalid_params}
            expect(response).to render_template("new")
          end
        end
      end
    end

  describe "PUT #update" do
    let (:new_params) {FactoryGirl.attributes_for(:task, :name => "Updated Name")}

    context "admin" do
      login_admin

        context "update with valid params" do

          it "will find the correct task" do
            task = Task.create! valid_params
            put :update, params: {:resource_controller => "projects", :resource_id => @project.id, id: task, task: new_params}
            task.reload
            expect(assigns(:task)).to eql(task)
            end


          it "will update the task" do
            task = Task.create! valid_params
            put :update, params: {:resource_controller => "projects", :resource_id => @project.id, id: task, task: new_params}
            task.reload
            expect(task.name).to eq new_params[:name]
            expect(task.created_at).to_not eql(task.updated_at)
            end

          it "will redirect to task page on success" do
            task = Task.create! valid_params
            put :update, params: {:resource_controller => "projects", :resource_id => @project.id, id: task, task: new_params}
            task.reload
            expect(response).to redirect_to(task_path(id: task))
          end
        end

        context "with invalid params" do

          it "will find the correct task" do
            task = Task.create! valid_params
            put :update, params: {:resource_controller => "projects", :resource_id => @project.id, id: task, task: new_params}
            task.reload
            expect(assigns(:task)).to eql(task)
            end

          it "will not update parameters" do
            task = Task.create! valid_params
            put :update, params: {:resource_controller => "projects", :resource_id => @project.id, id: task, task: invalid_params}
            task.reload
            expect(task.name).to_not eq(invalid_params[:name])
            expect(task.created_at).to eql(task.updated_at)
        end
          it "will re-render edit page" do
            task = Task.create! valid_params
            put :update, params: {:resource_controller => "projects", :resource_id => @project.id, id: task, task: invalid_params}
            task.reload
            expect(response).to render_template ("edit")
          end
        end
      end
    end

  describe "DELETE #destroy" do
    context "as admin" do
      login_admin

      it "will find the correct task" do
        task = Task.create! valid_params
        delete :destroy, params: {:resource_controller => "projects", :resource_id => @project.id, id: task}
        expect(assigns(:task)).to eql(task)
        end

      it "will delete the task" do
        task = Task.create! valid_params
        expect {
          delete :destroy, params: {:resource_controller => "projects", :resource_id => @project.id, id:task}
        }.to change(Task, :count).by(-1)
        end

      it "will redirect to tasks page" do
        task = Task.create! valid_params
        delete :destroy, params: {:resource_controller => "projects", :resource_id => @project.id, id: task}
        expect(response).to redirect_to(:action => :index)
      end
    end
  end
end
